#! /bin/bash

# test
#if [[ -L ~/.vim ]];then
#  echo hey
#else
#  echo poop
#fi

# Check and remove all previous symlinks/files and replace with new ones

# Check Vim
if [[ -L ~/.vim && -L ~/.vimrc ]]; then
  rm -r ~/.vim ~/.vimrc
  ln -s ~/gitrepos/dotfiles/vim/.vim ~/.vim
  ln -s ~/gitrepos/dotfiles/vim/.vimrc ~/.vimrc
else
  # Link up Vim files and directoris
  ln -s ~/gitrepos/dotfiles/vim/.vim ~/.vim
  ln -s ~/gitrepos/dotfiles/vim/.vimrc ~/.vimrc
fi

# Check BASH
#if [[ -L ~/.bash_profile && -L ~/.bashrc && -L ~/.inputrc && -L ~/.profile && -L ~/.mycd ]]; then
if [[ -d ~/.bashrc.d ]]; then
  rm -r ~/.bashrc.d
  ln -s ~/gitrepos/dotfiles/bash/.bashrc.d/ ~/.bashrc.d
else
  ln -s ~/gitrepos/dotfiles/bash/.bashrc.d/ ~/.bashrc.d
fi

if [[ -L ~/.bash_profile ]]; then
  rm ~/.bash_profile
  ln -s ~/gitrepos/dotfiles/bash/.bash_profile ~/.bash_profile
  source ~/.bash_profile
else
  ln -s ~/gitrepos/dotfiles/bash/.bash_profile ~/.bash_profile
  source ~/.bash_profile
fi

if [[ -L ~/.bashrc ]]; then
  rm ~/.bashrc
  ln -s ~/gitrepos/dotfiles/bash/.bashrc ~/.bashrc
  source ~/.bashrc
else
  ln -s ~/gitrepos/dotfiles/bash/.bashrc ~/.bashrc
  source ~/.bashrc
fi 

if [[ -L ~/.inputrc ]]; then
  rm ~/.inputrc
  ln -s ~/gitrepos/dotfiles/bash/.inputrc ~/.inputrc
  #bind -f ~/.inputrc
else
  ln -s ~/gitrepos/dotfiles/bash/.inputrc ~/.inputrc
  #bind -f ~/.inputrc
fi

if [[ -L ~/.profile ]]; then
  rm ~/.profile
  ln -s ~/gitrepos/dotfiles/bash/.profile ~/.profile
  source ~/.profile
else
  ln -s ~/gitrepos/dotfiles/bash/.profile ~/.profile
  source ~/.profile
fi

if [[ -L ~/.mycd ]]; then
  rm -r ~/.mycd
  ln -s ~/gitrepos/dotfiles/bash/.mycd/ ~/.mycd
else
  ln -s ~/gitrepos/dotfiles/bash/.mycd/ ~/.mycd
fi

# Check tmux
if [[ -L ~/.tmux.conf ]]; then
  rm ~/.tmux.conf
  ln -s ~/gitrepos/dotfiles/tmux/.tmux.conf ~/.tmux.conf
else
  # Link up tmux configuration file
  ln -s ~/gitrepos/dotfiles/tmux/.tmux.conf ~/.tmux.conf
fi

#sourcing tmux config file doesn't work..
#tmux source-Lile ~/.tmux.conf
