#! /bin/zsh

# Check and remove all previous symlinks/files and replace with new ones

# Check Vim
if [[ -d $HOME/.vim && ! -L $HOME/.vim ]]; then
  if [[ ! -d $HOME/backupDotfiles ]]; then
    mkdir $HOME/backupDotfiles
  fi
  mv $HOME/.vim $HOME/backupDotfiles
  ln -s $HOME/.dotfiles/vim/.vim $HOME/.vim
else
  if [[ -L $HOME/.vim ]]; then
    rm $HOME/.vim
  fi
  ln -s $HOME/.dotfiles/vim/.vim $HOME/.vim
fi
#----------------------------------------------------------------------------------------------------
if [[ -f $HOME/.vimrc && ! -L $HOME/.vimrc ]]; then
  if [[ ! -d $HOME/backupDotfiles ]]; then
    mkdir $HOME/backupDotfiles
  fi
  mv $HOME/.vimrc $HOME/backupDotfiles
  ln -s $HOME/.dotfiles/vim/.vimrc $HOME/.vimrc
else
  if [[ -L $HOME/.vimrc ]]; then
    rm $HOME/.vimrc
  fi
  ln -s $HOME/.dotfiles/vim/.vimrc $HOME/.vimrc
fi
#----------------------------------------------------------------------------------------------------
# Check BASH
if [[ -f $HOME/.zshrc && ! -L $HOME/.zshrc ]]; then
  if [[ ! -d $HOME/backupDotfiles ]]; then
    mkdir $HOME/backupDotfiles
  fi
  mv $HOME/.zshrc $HOME/backupDotfiles
  ln -s $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc
else
  if [[ -L $HOME/.zshrc ]]; then
    rm $HOME/.zshrc
  fi
  ln -s $HOME/.dotfiles/zsh/.zshrc $HOME/.zshrc
fi
#----------------------------------------------------------------------------------------------------
if [[ -d $HOME/.zshrc.d && ! -L $HOME/.zshrc.d ]]; then
  if [[ ! -d backupDotfiles ]]; then
    mkdir backupDotfiles
  fi
  mv $HOME/.zshrc.d $HOME/backupDotfiles
  ln -s $HOME/.dotfiles/zsh/.zshrc.d $HOME/.zshrc.d
else
  if [[ -L $HOME/.zshrc.d ]]; then
    rm $HOME/.zshrc.d
  fi
  ln -s $HOME/.dotfiles/zsh/.zshrc.d $HOME/.zshrc.d
fi
##----------------------------------------------------------------------------------------------------
#if [[ -f $HOME/.zsh_profile && ! -L $HOME/.zsh_profile ]]; then
#  if [[ ! -d backupDotfiles ]]; then
#    mkdir backupDotfiles
#  fi
#  mv $HOME/.zsh_profile $HOME/backupDotfiles
#else
#  if [[ -L $HOME/.zsh_profile ]]; then
#    rm $HOME/.zsh_profile
#  fi
#  ln -s $HOME/.dotfiles/zsh/.zsh_profile $HOME/.zsh_profile
#fi
##----------------------------------------------------------------------------------------------------
#if [[ -f $HOME/.inputrc && ! -L $HOME/.inputrc ]]; then
#  if [[ ! -d backupDotfiles ]]; then
#    mkdir backupDotfiles
#  fi
#  mv $HOME/.inputrc $HOME/backupDotfiles
#else
#  if [[ -L $HOME/.inputrc ]]; then
#    rm $HOME/.inputrc
#  fi
#  ln -s $HOME/.dotfiles/zsh/.inputrc $HOME/.inputrc
#fi
##----------------------------------------------------------------------------------------------------
#if [[ -f $HOME/.profile && ! -L $HOME/.profile ]]; then
#  if [[ ! -d backupDotfiles ]]; then
#    mkdir backupDotfiles
#  fi
#  mv $HOME/.profile $HOME/backupDotfiles
#else
#  if [[ -L $HOME/.profile ]]; then
#    rm $HOME/.profile
#  fi
#  ln -s $HOME/.dotfiles/zsh/.profile $HOME/.profile
#fi
#----------------------------------------------------------------------------------------------------
# Check tmux
if [[ -f $HOME/.tmux.conf && ! -L $HOME/.tmux.conf ]]; then
  if [[ ! -d backupDotfiles ]]; then
    mkdir backupDotfiles
  fi
  mv $HOME/.tmux.conf $HOME/backupDotfiles
else
  if [[ -L $HOME/.tmux.conf ]]; then
    rm $HOME/.tmux.conf
  fi
  ln -s $HOME/.dotfiles/tmux/.tmux.conf $HOME/.tmux.conf
fi
